name: Build and Push Docker Image to Google Cloud

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch (or any branch you prefer)

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Java (with distribution)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'  # Add this line to specify the distribution

    # Build the JAR using Maven (adjust the command if you're using Gradle)
    - name: Build JAR with Maven
      run: mvn clean package -DskipTests

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Google Cloud
    - name: Set up GCP credentials
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    # Configure Docker to use Google Cloud
    - name: Configure Docker to use Google Cloud
      run: |
        gcloud auth configure-docker gcr.io

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-app:${{ github.sha }} .

    # Push the Docker image to GCR
    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-app:${{ github.sha }}
