name: Build and Push Docker Image to GCP

on:
  push:
    branches: 
      - main

jobs:
  build-push-gcr:
    name: Build and Push Docker Image to GCP
    runs-on: ubuntu-latest  # The runner will use an Ubuntu environment
    
    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Google Cloud SDK and authenticate using the service account key
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}  # Secret storing the GCP service account key
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # GCP project ID stored in GitHub secrets
        export_default_credentials: true  # Export default credentials for gcloud CLI

    # Step 3: Build the Docker image (modify as per your specific requirements)
    - name: Build Docker image
      run: docker build -t test-deploy-cicd-gke:latest .

    # Step 4: Authenticate Docker with Google Container Registry (GCR)
    - name: Authenticate Docker to GCR
      run: gcloud auth configure-docker --quiet

    # Step 5: Tag Docker image and push it to Google Container Registry (GCR)
    - name: Tag and push Docker image to GCR
      run: |
        docker tag test-deploy-cicd-gke:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/test-deploy-cicd-gke:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/test-deploy-cicd-gke:latest