name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Login to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker to use GCR
      run: |
        gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/deployment-k8s-gke-demo/test-deploy-cicd-gke:$GITHUB_SHA .
        docker push gcr.io/deployment-k8s-gke-demo/test-deploy-cicd-gke:$GITHUB_SHA

    - name: Logout from Google Cloud
      run: gcloud auth revoke