name: Setup Google Cloud SDK and Authenticate

on:
  push:
    branches:
      - main

jobs:
  setup-google-cloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug environment variables
      run: printenv

    - name: Authenticate with Google Cloud
      run: |
        if [ -z "$SERVICE_ACCOUNT_KEY" ]; then
          echo "Error: SERVICE_ACCOUNT_KEY is empty!" && exit 1
        fi
        echo "$SERVICE_ACCOUNT_KEY" > /tmp/keyfile.json
        cat /tmp/keyfile.json  # Debug the key content to ensure it's correctly written
        gcloud auth activate-service-account --key-file=/tmp/keyfile.json
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Set project
      run: gcloud config set project ${{ secrets.PROJECT_ID }}
